/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;

import java.util.Scanner;

public class App {

    public void promocao(Produto prod) {
        System.out.println("o produto " + prod.getNome() + " está na promocao por " + prod.getPreco());
    }

    public static void main(String[] args) {
        System.out.println("Hello World");
        Scanner sc = new Scanner(System.in);
        /*
        int idade = 31;
        double altura = 1.76;
        String nome = "Henrique";
        char inicial = 'H';
        boolean souEstudante = true;
         */
 /*
        int numero = 0;
        
        if (numero > 0) {
            System.out.println("O núumero é positivo");
        } else if (numero == 0) {
            System.out.println("O número é zero");
        } else {
            System.out.println("O número é negativo");
         */

 /*
        int diasSemana = 5;

        switch (diasSemana) {
            case 1:
                System.out.println("domingo");
                break;
            case 2:
                System.out.println("segunda-feira");
                break;
            case 3:
                System.out.println("terça-feira");
                break;
            case 4:
                System.out.println("quarta-feira");
                break;
            case 5:
                System.out.println("quinta-feira");
                break;
            case 6:
                System.out.println("sexta-feira");
                break;
            case 7:
                System.out.println("sabado");
                break;
            default:
                System.out.println("dia invalido");
                break;
        }
         */
 /*
        int numero2 = 2;
        String resultado = (numero2 % 2 == 0) ? "Par" : "Ímpar";
        System.out.println("o número é " + resultado);
         */
 /*
        int voltas = 0;
        while (voltas < 10) {
            System.out.println("Pedale, você já deu " + voltas + " voltas");
            voltas++;
        }
        System.out.println("você chegou no final");
         */
 /*
        for (int i = 0; i < 10; i++) {
            System.out.println(i);
        }
         */
 /*
 test meuTest=new test();
 meuTest.somar(1,2);
         */
 /*
        Pessoa Joao = new Pessoa("joão", 30);
        Joao.caminhar();
        
        Produto meuProd = new Produto("livro", 49.99);
        System.out.println(meuProd.getNome());

        App meuApp = new App();
        meuApp.promocao(meuProd);
         */
 /*
        int numero1, numero2;
        System.out.println("digite um numero");
        numero1 = sc.nextInt();
        System.out.println("digite outro numero");
        numero2 = sc.nextInt();
        System.out.println("resultado " + (numero1 + numero2));
        sc.close();
         */
        String nome, sobrenome;
        System.out.println("qual o seu nome?");
        nome = sc.nextLine();
        System.out.println("qual o seu sobrenome?");
        sobrenome = sc.nextLine();
        System.out.println("ola " + nome + ' ' + sobrenome + '!');
    }
}
